version: '2'

services:
  backend-1:
    image: cassandra:${CASSTAG}
    container_name: backend-1
    networks:
      - backend
    ports:
      - 9042:9042
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=backend-1
      - CASSANDRA_CLUSTER_NAME=backend
  backend-2:
    image: cassandra:${CASSTAG}
    container_name: backend-2
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - backend-1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=backend-1
      - CASSANDRA_CLUSTER_NAME=backend
  backend-3:
    image: cassandra:${CASSTAG}
    container_name: backend-3
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - backend-2
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=backend-1
      - CASSANDRA_CLUSTER_NAME=backend
  stargate:
    image: stargateio/stargate-4_0:${SGTAG}
    container_name: stargate
    depends_on:
      - backend-1
    networks:
      - backend
    ports:
      - 10004:9042
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8085:8085
    mem_limit: 2G
    environment:
      - JAVA_OPTS="-Xmx2G" -Dstargate.auth_tokenttl=8000 -Dstargate.graphql_first.enabled=true
      - CLUSTER_NAME=backend
      - CLUSTER_VERSION=4.0
      - SEED=backend-1
      - SIMPLE_SNITCH=true
      - ENABLE_AUTH=true
  zeppelin:
    image: apache/zeppelin:${ZEPPTAG}
    container_name: zeppelin
    depends_on:
      - backend-1
    networks:
      - backend
    ports:
      - 18080:8080
networks:
  backend:
